<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ddl3rdPartyAdServer</name>
   <tag></tag>
   <elementGuidId>9fb8e692-1cce-4d0c-be53-ece6e19e74fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//label[.='AdServing']/../..//span[@class='Select-multi-value-wrapper'])[1]</value>
   </webElementProperties>
</WebElementEntity>
