<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TxtSearchBox</name>
   <tag></tag>
   <elementGuidId>4a7b0077-e73c-4ca8-a091-f3cef4581817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_Content_tabWidgetControl_tabSearch_txtSearchCampaign</value>
   </webElementProperties>
</WebElementEntity>
