<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ReactSelect</name>
   <tag></tag>
   <elementGuidId>fb1dcfa9-e49f-426f-8c7b-55033c440bd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@role='listbox']/div[.='${value}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>$&quot;//*[@role='listbox']/div[.='{value}']&quot;</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@role='listbox']/div[.='${value}']</value>
   </webElementProperties>
</WebElementEntity>
